/*
 * sprites.c
 *
 *  Created on: Jul 10, 2025
 *      Author: PR108
 */

#include "lcd.h"



//size 12x12
static const uint16_t sprite_player[] = {
BLACK, BLACK, BLACK, BLACK, BLACK, GREEN, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, BLACK, GREEN, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK, BLACK, BLACK,
BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK,
GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN,
GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN,
GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN,
GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN,
GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN,
GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN,
};
//size 3x4
static const uint16_t sprite_bullet[] = {
BLACK, RED, BLACK,
RED, RED, RED,
RED, RED, RED,
RED, RED, RED,
};

//size 3x4
static const uint16_t sprite_enemy_bullet[] = {
BLUE, BLUE, BLUE,
BLUE, BLUE, BLUE,
BLUE, BLUE, BLUE,
BLACK, BLUE, BLACK,
};
//size 12x8
static const uint16_t sprite_crab[] = {
BLACK, BLACK, CYAN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, CYAN, BLACK, BLACK,
BLACK, BLACK, BLACK, CYAN, BLACK, BLACK, BLACK, BLACK, CYAN, BLACK, BLACK, BLACK,
BLACK, BLACK, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, BLACK, BLACK,
BLACK, CYAN, CYAN, BLACK, CYAN, CYAN, CYAN, CYAN, BLACK, CYAN, CYAN, BLACK,
CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN,
CYAN, BLACK, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, BLACK, CYAN,
CYAN, BLACK, CYAN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, CYAN, BLACK, CYAN,
BLACK, BLACK, BLACK, CYAN, CYAN, BLACK, BLACK, CYAN, CYAN, BLACK, BLACK, BLACK,
};

static const uint16_t sprite_crab_2[] = {
BLACK, BLACK, CYAN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, CYAN, BLACK, BLACK,
CYAN,  BLACK, BLACK,CYAN,  BLACK, BLACK, BLACK, BLACK, CYAN,  BLACK,BLACK, CYAN,
CYAN,  BLACK, CYAN, CYAN,  CYAN,  CYAN,  CYAN,  CYAN,  CYAN,  CYAN, BLACK, CYAN,
CYAN,  CYAN,  CYAN, BLACK, CYAN,  CYAN,  CYAN,  CYAN,  BLACK, CYAN, CYAN,  CYAN,
CYAN,  CYAN,  CYAN, CYAN,  CYAN,  CYAN,  CYAN,  CYAN,  CYAN,  CYAN, CYAN,  CYAN,
BLACK,  BLACK, CYAN, CYAN,  CYAN,  CYAN,  CYAN,  CYAN,  CYAN,  CYAN, BLACK, BLACK,
BLACK,  BLACK, CYAN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, CYAN, BLACK, BLACK,
BLACK,  CYAN,  BLACK,BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,CYAN,  BLACK,
};

// size 12x8
static const uint16_t sprite_explosion[] = {
BLACK, BLACK, YELLOW, ORANGE, ORANGE, YELLOW, YELLOW, ORANGE, ORANGE, YELLOW, BLACK, BLACK,
BLACK, YELLOW, ORANGE, RED,    RED,    ORANGE, ORANGE, RED,    RED,    ORANGE, YELLOW, BLACK,
YELLOW, ORANGE, RED,    WHITE, WHITE,  RED,    RED,    WHITE,  WHITE,  RED,    ORANGE, YELLOW,
ORANGE, RED,    WHITE,  WHITE, WHITE,  WHITE,  WHITE,  WHITE,  WHITE,  WHITE,  RED,    ORANGE,
ORANGE, RED,    WHITE,  WHITE, WHITE,  WHITE,  WHITE,  WHITE,  WHITE,  WHITE,  RED,    ORANGE,
YELLOW, ORANGE, RED,    WHITE, WHITE,  RED,    RED,    WHITE,  WHITE,  RED,    ORANGE, YELLOW,
BLACK, YELLOW, ORANGE, RED,    RED,    ORANGE, ORANGE, RED,    RED,    ORANGE, YELLOW, BLACK,
BLACK, BLACK, YELLOW, ORANGE, ORANGE, YELLOW, YELLOW, ORANGE, ORANGE, YELLOW, BLACK, BLACK,
};

static const uint16_t sprite_squid[] = {
BLACK, BLACK, BLACK, BLACK, BLACK, MAGENTA, MAGENTA, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, MAGENTA, MAGENTA, MAGENTA, MAGENTA, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, MAGENTA, MAGENTA, MAGENTA, MAGENTA, MAGENTA, MAGENTA, BLACK, BLACK, BLACK,
BLACK, BLACK, MAGENTA, MAGENTA, BLACK, MAGENTA, MAGENTA, BLACK, MAGENTA, MAGENTA, BLACK, BLACK,
BLACK, BLACK, MAGENTA, MAGENTA, MAGENTA, MAGENTA, MAGENTA, MAGENTA, MAGENTA, MAGENTA, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, MAGENTA, BLACK, BLACK, MAGENTA, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, MAGENTA, BLACK, MAGENTA, MAGENTA, BLACK, MAGENTA, BLACK, BLACK, BLACK,
BLACK, BLACK, MAGENTA, BLACK, MAGENTA, BLACK, BLACK, MAGENTA, BLACK, MAGENTA, BLACK, BLACK,
};

static const uint16_t sprite_squid_2[] = {
BLACK, BLACK, BLACK, BLACK, BLACK, MAGENTA, MAGENTA, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, MAGENTA, MAGENTA, MAGENTA, MAGENTA, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, MAGENTA, MAGENTA, MAGENTA, MAGENTA, MAGENTA, MAGENTA, BLACK, BLACK, BLACK,
BLACK, BLACK, MAGENTA, MAGENTA, BLACK, MAGENTA, MAGENTA, BLACK, MAGENTA, MAGENTA, BLACK, BLACK,
BLACK, BLACK, MAGENTA, MAGENTA, MAGENTA, MAGENTA, MAGENTA, MAGENTA, MAGENTA, MAGENTA, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, MAGENTA, BLACK, BLACK, MAGENTA, BLACK, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, MAGENTA, BLACK, BLACK, BLACK, BLACK, MAGENTA, BLACK, BLACK, BLACK,
BLACK, BLACK, BLACK, BLACK, MAGENTA, BLACK, BLACK, MAGENTA, BLACK, BLACK, BLACK, BLACK,
};

static const uint16_t sprite_octopus[] = {
BLACK, BLACK, BLACK, BLACK, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLACK,
YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW,
YELLOW, YELLOW, YELLOW, BLACK, BLACK, YELLOW, YELLOW, BLACK, BLACK, YELLOW, YELLOW, YELLOW,
YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW,
BLACK, BLACK, BLACK, YELLOW, YELLOW, BLACK, BLACK, YELLOW, YELLOW, BLACK, BLACK, BLACK,
BLACK, BLACK, YELLOW, YELLOW, BLACK, YELLOW, YELLOW, BLACK, YELLOW, YELLOW, BLACK, BLACK,
YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, YELLOW, YELLOW,
};

static const uint16_t sprite_octopus_2[] = {
BLACK, BLACK, BLACK, BLACK, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK,
BLACK, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLACK,
YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW,
YELLOW, YELLOW, YELLOW, BLACK, BLACK, YELLOW, YELLOW, BLACK, BLACK, YELLOW, YELLOW, YELLOW,
YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW,
BLACK, BLACK, BLACK, YELLOW, YELLOW, BLACK, BLACK, YELLOW, YELLOW, BLACK, BLACK, BLACK,
BLACK, BLACK, YELLOW, YELLOW, BLACK, YELLOW, YELLOW, BLACK, YELLOW, YELLOW, BLACK, BLACK,
BLACK, BLACK, BLACK, YELLOW, YELLOW, BLACK, BLACK, YELLOW, YELLOW, BLACK, BLACK, BLACK,
};
